const LABELS: Record<string, string> = {
  PENDING: 'Pendiente',
  GENERATED: 'Generado',
  UPLOADED: 'Cargado',
  VALIDATED: 'Validado',
  REJECTED: 'Rechazado',
  WAIVED: 'No aplica',
  ENVIADO_COMO_ANEXO_INFORMATIVO: 'Enviado como anexo informativo',
  PENDIENTE_USO_POST_VIAJE: 'Pendiente de uso post-viaje',
  PENDIENTE_CLASIFICACION: 'Pendiente clasificacion',
  AUTORIZACION_RECIBIDA: 'Autorizacion recibida',
  PENDIENTE_VALIDACION_AMPARO: 'Pendiente validacion Amparo',
  VALIDADO_POR_AMPARO: 'Validado por Amparo',
  DEVUELTO_POR_AMPARO: 'Devuelto por Amparo',
  RECHAZADO_POR_AMPARO: 'Rechazado por Amparo',
  INSTRUCCION_RECIBIDA: 'Instruccion recibida',
  SIN_MEMORANDO_JUSTIFICADO: 'Sin memorando justificado',
  VIAJE_IMPREVISTO: 'Viaje imprevisto',
  FUERA_PLAZO_MAPRE: 'Fuera de plazo MAPRE',
  PENDIENTE_DESIGNACION: 'Pendiente designacion',
  MEMORANDO_PRESIDENCIA: 'Memorando Presidencia',
  CORREO_INSTRUCCION: 'Correo de instruccion',
  INSTRUCCION_DIRECTA_RI: 'Instruccion directa RI',
  MATRIZ_PROGRAMADA_CONFIRMADA: 'Matriz programada confirmada',
  OTRO: 'Otro',
  MEMORANDO_FORMAL: 'Memorando formal',
  CORREO_AMPARO: 'Correo de Amparo',
  CORREO_PRESIDENCIA: 'Correo de Presidencia',
  CORREO_DIRECTOR_SECRETARIA: 'Correo director/secretaria',
  INSTRUCCION_VERBAL_REGISTRADA: 'Instruccion verbal registrada',
  WHATSAPP: 'WhatsApp',
  NORMAL: 'Normal',
  ADVERTENCIA: 'Advertencia',
  CRITICO: 'Critico',
  FUERA_DE_PLAZO: 'Fuera de plazo',
  MATRIZ_REGISTRADA: 'Matriz registrada',
  PENDIENTE_PAUTA_RI: 'Pendiente pauta RI',
  PAUTA_RI_DADA: 'Pauta RI dada',
  CONVERTIDO_A_CASO: 'Convertido a expediente',
  DESIGNACION_BORRADOR: 'Borrador de designacion',
  DESIGNACION_GENERADA: 'Designacion generada',
  DESIGNACION_ENVIADA: 'Designacion enviada',
  PENDIENTE_ACEPTACION_COLABORADOR: 'Pendiente aceptacion del colaborador',
  COLABORADOR_ACEPTO: 'Colaborador acepto',
  COLABORADOR_RECHAZO: 'Colaborador rechazo',
  PENDIENTE_DOCUMENTOS: 'Pendiente de documentos',
  DOCUMENTOS_EN_REVISION: 'Documentos en revision',
  DOCUMENTOS_COMPLETOS: 'Documentos completos',
  FORMULARIO_EN_ELABORACION: 'Formulario en elaboracion',
  CARTA_EN_ELABORACION: 'Carta en elaboracion',
  EXPEDIENTE_ARMADO: 'Expediente armado',
  ENVIADO_MAPRE: 'Enviado a MAPRE',
  DESPACHO_REVIEW: 'Revision de Despacho',
  CONSEJO_DIRECTIVO_FIRMA: 'Firma del Consejo Directivo',
  EXPEDIENTE_FIRMADO_RECIBIDO: 'Expediente firmado recibido',
  COORDINACION_ADMINISTRATIVA: 'Coordinacion administrativa',
  VIAJE_REALIZADO: 'Viaje realizado',
  PENDIENTE_INFORME_Y_LIQUIDACION: 'Pendiente informe y liquidacion',
  PENDIENTE_LIQUIDACION: 'Pendiente liquidacion',
  LIQUIDACION_EN_REVISION: 'Liquidacion en revision',
  LIQUIDACION_REQUIERE_CORRECCION: 'Liquidacion requiere correccion',
  LIQUIDACION_APROBADA: 'Liquidacion aprobada',
  NO_APLICA_LIQUIDACION: 'No aplica liquidacion',
  CANCELLED: 'Cancelado',
  FIRMA_DIGITAL_PENDIENTE_JUSTIFICACION: 'Pendiente justificacion de firma digital',
  RECEIVED: 'Recibido',
  AUTHORIZATION_VALIDATION: 'Validacion de autorizacion',
  AUTHORIZATION_CORRECTION: 'Correccion de autorizacion',
  DESIGNATION: 'Designacion',
  COLLABORATOR_ACCEPTANCE: 'Aceptacion del colaborador',
  DOCUMENT_COLLECTION: 'Recoleccion documental',
  DOCUMENT_REVIEW: 'Revision documental',
  FORMULARIO_SOLICITUD: 'Formulario de solicitud',
  CARTA_MINISTRO: 'Carta al Ministro',
  EXPEDIENTE_REVIEW: 'Revision del expediente',
  EXPEDIENTE_FIRMADO_RECEIPT: 'Recepcion del expediente firmado',
  POST_TRAVEL: 'Post viaje',
  LIQUIDATION_REVIEW: 'Revision de liquidacion',
  CLOSURE: 'Cierre',
  DOCS_VALIDATION: 'Validacion documental',
  TECH_REVIEW: 'Revision tecnica',
  MANAGER_APPROVAL: 'Aprobacion gerencial',
  FINANCE_APPROVAL: 'Aprobacion financiera',
  HR_APPROVAL: 'Aprobacion de RRHH',
  APPROVED: 'Aprobado',
  NEEDS_INFO: 'Requiere informacion',
  CLOSED: 'Cerrado',
  DRAFT: 'Borrador',
  SENT: 'Enviado',
  ACCEPTED: 'Aceptado',
  EXPIRED: 'Expirado',
}

export function labelFor(value?: string | null) {
  if (!value) return 'Por definir'
  return LABELS[value] || value
}

